---
title: "Inscriptions"
description: "<strong>Inscriptions pour la reunion PEV-AC</strong>"
#image: /static/img/pen-nib-solid.svg
title-block-banner: false
execute: 
  echo: false
---


Chers participants et modérateurs,

Nous sommes ravis de vous accueillir à Kinshasa! Pour garantir une expérience fluide, veuillez vous enregistrer en suivant les étapes ci-dessous :

- **Remplissez le formulaire** :
Entrez vos coordonnées (nom, prénom, adresse e-mail, etc.).
- **Validez votre inscription** :
Cliquez sur le bouton **“Envoyer”** pour confirmer votre participation.
- **Téléchargez le calendrier**:
Accedez a la section *Other Links* et cliquez sur **Télécharger Agenda** (à droite de votre écran), puis suivez les instructions d’installation pour ajouter le calendrier à votre application de gestion de calendrier préférée (par exemple, Outlook, Google Calendar, etc.).
N’hésitez pas à nous contacter si vous avez des questions ou des préoccupations. Nous avons hâte de vous retrouver lors de notre événement !
<br/>
<br/>
<br/>

```{=html}
<iframe src="https://fm.addxt.com/form/?vf=1FAIpQLSclCYRAbO5Y8gF-rhvDnnpuOP3PP3GHud50KBYlea9U-3563w" width="1080" height="1240" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

```











